ground_z: -0.035
X_tip_body:
  x: 0.00922753
  y: 0.00883189
  z: 0.659304
X_tcp_cage:
  x: 0
  y: 0
  z: -0.123926
hover_above_tip: 0.08
insert_below_tip: 0.03
topple:
  forward: 0.2
  downward: 0.03
zigzag:
  step_forward: 0.1
  step_sideways: 0.1
  cycles: 5
  max_vel: 1
  max_acc: 0.5
cone:
  radius: 0.15
  apex: 0.8
  height: 1