#ground_z: -0.035
ground_z: -0.04
X_tcp_cage:
  x: 0.000548455
  y: 0.00354947
  z: -0.194698
flu_T_tcp:
  x: -0.07
  y: 0
  z: -0.114698
insert_below_tip: 0.1
rnw:
  hover_above_tip: 0.03
  insertion_depth: 0.12 # 0.11
  topple_init: 0.05
  desired_nutation: 30
  desired_grip_depth: 0.05
  tau: 40
  max_vel: 0.5
  max_acc: 0.3
  rocking_max_vel: 1
  rocking_max_acc: 0.5
  adjust_nutation_threshold: 5
  adjust_grip_depth_threshold: 0.05
topple:
  forward: 0.4
  downward: 0.05
zigzag:
  step_forward: 0.1
  step_sideways: 0.1
  cycles: 5
  max_vel: 1
  max_acc: 0.5
cone:
  radius: 0.15
  apex: 0.8
  height: 1
  base_center:
    x: -0.0530555
    y: 0.013382
    z: -0.223705
  tip:
    x: 0.0959235
    y: 0.0158244
    z: 0.777391